name = "The Conglomerate"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15a74cc297476836f3f62a133e5c79aba2c742a2f7dfb051b84196dde626583a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.139"
