name = "The Conglomerate"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e50c2935e96e6c293e618db8923c0fbc07ede2e7ab3b4cb93fe1d1a0a866fab8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.139"
