name = "The Conglomerate"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7597ce259e7095529618cd01bb6728084f8e646aa1992361629b8c58bc5cff47"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.139"
