name = "The Conglomerate"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c4d7ba5f8ee65b269abd127b161f29e09f6657551eb3d4d82a785074fcd8a8f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.139"
