name = "The Conglomerate"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd6fa2ebfa394c24ec4a57fee9ddcf1bf9112f0ffc265f9cedaf830c3cfab0d3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.139"
