name = "The Conglomerate"
author = "SillviaTV, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d567d208d1fda524684bd268b4f4ebd0363c04abe4ac99166a3cc8b175e0d6f9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.139"
